services:
  postgres_cash_transfer_db_test:
    image: postgres
    container_name: postgres_cash_transfer_db_test
    restart: always
    ports:
      - 5544:5432
    env_file:
      - .env.docker.test

  node_cash_transfer_app:
    container_name: node_cash_transfer_app
    build: ./back_end/
    ports:
      - 5000:5000
    depends_on:
      - postgres_cash_transfer_db_test
    env_file:
      - .env.docker.test
